#!/bin/sh

arch=$(uname -m)

# Sleep 10s to prevent tight loop in case of failure
echo "PacketStream client is starting..."
sleep 10

case $arch in
  x86_64)
    echo "Starting x86_64 PacketStream client..."
    exec /usr/local/bin/linux_amd64/psclient "$@"
    ;;
  i386)
    echo "Starting i386 PacketStream client..."
    exec /usr/local/bin/linux_386/psclient "$@"
    ;;
  armv6l)
    echo "Starting armv6l PacketStream client..."
    exec /usr/local/bin/linux_arm/psclient "$@"
    ;;
  armv7l)
    echo "Starting armv7l PacketStream client..."
    exec /usr/local/bin/linux_arm/psclient "$@"
    ;;
  armv8l)
    echo "Starting armv8l PacketStream client..."
    exec /usr/local/bin/linux_arm/psclient "$@"
    ;;
  aarch64)
    echo "Starting aarch64 PacketStream client..."
    exec /usr/local/bin/linux_arm64/psclient "$@"
    ;;
  *)
    echo "PacketStream: Unsupported architecture: $arch"
    exit 1
    ;;
esac
